#!/bin/bash
sudo apt update
sudo apt install python3-pip -y
sudo apt install python3-dev -y  
sudo apt install nginx -y
sudo apt install python3-django -y
sudo pip install django gunicorn
sudo pip3 install virtualenv 
mkdir /home/projectdir
cd /home/projectdir || exit
virtualenv env
source env/bin/activate
sudo django-admin startproject textutils ~/projectdir
sudo /home/projectdir/manage.py makemigrations
sudo /home/projectdir/manage.py migrate
deactivate
